apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "web-app"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "secret/mysql/config"
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{`{{- with secret "secret/mysql/config" -}}
            export url#mysql://{{.Data.data.MYSQL_USER}}:{{.Data.data.MYSQL_PASSWORD}}@mysql/testdb?charset=utf8_general_ci&timezone=-0700
          {{- end }}`}}
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: web-app
      containers:
      - image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
        name: {{ .Values.name }}
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: JWT_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: SERVICE_PORT
          value: "8080"
        ports:
        - containerPort: 3000
          name: {{ .Values.name }}