apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: vault
      containers:
      - image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
        name: {{ .Values.name }}
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_DATABASE
          value: "testdb"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: vault:secret/data/mysql/config#MYSQL_USER
        - name: MYSQL_PASSWORD
          value: vault:secret/data/mysql/config#MYSQL_PASSWORD
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: JWT_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: SERVICE_PORT
          value: "8080"
        ports:
        - containerPort: 3000
          name: {{ .Values.name }}