apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - name: {{ .Values.name }}
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Values.name }}
  clusterIP: None
